#!/bin/bash

# $DOCKERFILE_PATH and $IMAGE_NAME are injected into the build

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             -f $DOCKERFILE_PATH \
             -t $IMAGE_NAME .
